plugins {
    id 'java'
    id 'org.wpilib.WPILibRepositoriesPlugin' version '2027.0.0'
    id 'maven-publish'
    id("net.ltgt.errorprone") version "4.2.0"
    id "com.diffplug.spotless" version "8.9.0"
}

group = 'team1306'

repositories {
    mavenCentral()
    maven {
        url "https://maven.ctr-electronics.com/release/"
    }
    maven {
        url "https://frcmaven.wpi.edu/artifactory/littletonrobotics-mvn-release/"
    }
}

if (project.hasProperty('releaseMode')) {
    wpilibRepositories.addAllReleaseRepositories(project)
} else {
    wpilibRepositories.addAllDevelopmentRepositories(project)
}
wpilibRepositories.use2027Repos()

def wpilibVersion = "2027.+"
def advantageKitVersion = "27.0.0-alpha-4"
def pheonix6Version = "26.50.0-alpha-1";

dependencies {
    compileOnly "org.wpilib:commands3-java:$wpilibVersion"

    compileOnly "org.wpilib.ntcore:ntcore-java:$wpilibVersion"
    compileOnly "org.wpilib.wpiunits:wpiunits-java:$wpilibVersion"
    compileOnly "org.wpilib.wpimath:wpimath-java:$wpilibVersion"
    compileOnly "org.wpilib.wpilibj:wpilibj-java:$wpilibVersion"
    compileOnly "org.wpilib.wpiutil:wpiutil-java:$wpilibVersion"
    compileOnly "org.wpilib.hal:hal-java:$wpilibVersion"

    compileOnly "com.ctre.phoenix6:wpiapi-java:$pheonix6Version"
    compileOnly "org.littletonrobotics.akit:akit-java:$advantageKitVersion"

    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'

    compileOnly 'com.google.auto.service:auto-service:1.0-rc5'
    annotationProcessor 'com.google.auto.service:auto-service:1.0-rc5'

    errorprone("com.google.errorprone:error_prone_core:2.37.0")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation "org.wpilib:commands3-java:$wpilibVersion"
    testImplementation "org.wpilib.wpiunits:wpiunits-java:$wpilibVersion"
    testImplementation "org.wpilib.wpimath:wpimath-java:$wpilibVersion"
    testImplementation "org.wpilib.wpilibj:wpilibj-java:$wpilibVersion"
    testImplementation "org.wpilib.wpiutil:wpiutil-java:$wpilibVersion"

    testImplementation "com.ctre.phoenix6:wpiapi-java:$pheonix6Version"
    testImplementation "org.littletonrobotics.akit:akit-java:$advantageKitVersion"

    testImplementation 'us.hebi.quickbuf:quickbuf-runtime:1.4'
}

test {
    useJUnitPlatform()
}


publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            groupId = "com.github.team1306"
            artifactId = "badger-log"
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:processing'
}

tasks.withType(Javadoc) {
    options {
        docTitle = "Badger Utils Javadoc"
    }
}


javadoc {
    exclude 'com.fasterxml.jackson.annotation.JsonAutoDetect'
}

test {
    useJUnitPlatform()
}

apply plugin: 'groovy'

// Spotless formatting
project.compileJava.dependsOn(spotlessApply)
spotless {
    java {
        target fileTree(".") {
            include "**/*.java"
            exclude "**/build/**", "**/build-*/**"
        }
        toggleOffOn()
        googleJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
    groovyGradle {
        target fileTree(".") {
            include "**/*.gradle"
            exclude "**/build/**", "**/build-*/**"
        }
        greclipse()
        indentWithSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
    json {
        target fileTree(".") {
            include "**/*.json"
            exclude "**/build/**", "**/build-*/**"
        }
        gson().indentWithSpaces(2)
    }
    format "misc", {
        target fileTree(".") {
            include "**/*.md", "**/.gitignore"
            exclude "**/build/**", "**/build-*/**"
        }
        trimTrailingWhitespace()
        indentWithSpaces(2)
        endWithNewline()
    }
}
